apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clientapp-ingress  
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"    
    nginx.org/mergeable-ingress-type: "master"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /clientapp(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: clientapp-service
            port:
              number: 80
      - path: /operatorapp(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: operatorapp-service
            port:
              number: 80
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: clientapp-service
            port:
              number: 80