
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unconfirmed-pv
  labels:
    type: local
spec:
  storageClassName: azurefile
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unconfirmed"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: confirmed-pv
  labels:
    type: local
spec:
  storageClassName: azurefile
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/confirmed"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: published-pv
  labels:
    type: local
spec:
  storageClassName: azurefile
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/published"
