apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
  - name: rabbitmq
    image: devappacr1980.azurecr.io/rabbitmq:latest
    ports:
    - containerPort: 5672
    - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - name: rmqport
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: dashboard-port
    protocol: TCP
    port: 15672
    targetPort: 15672  


