apiVersion: v1
kind: Service
metadata:
  name: antivirusapp-service
spec:
  type: ClusterIP
  selector:
    app: antivirusapp
  ports:
  - name: antivirusapp-port
    protocol: TCP
    port: 80
    targetPort: 80  
